/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUICadastroEspeciePagamento.java
 *
 * Created on 17/02/2011, 22:12:01
 */

package visao.gui;

import excecao.PessoaisException;
import java.awt.Dimension;
import java.text.DateFormat;
import modelo.dominio.EspeciePagamento;
import modelo.dominio.constante.Constante;
import modelo.dominio.constante.OperacaoEspeciePagamento;
import modelo.dominio.constante.TipoContaEspeciePagamento;

/**
 *
 * @author Marlon
 */
public class GUICadastroEspeciePagamento extends javax.swing.JInternalFrame {

    /** Creates new form GUICadastroEspeciePagamento */
    public GUICadastroEspeciePagamento() {
        initComponents();
        for (OperacaoEspeciePagamento operacao_especie_pagamento : OperacaoEspeciePagamento.values() ){
          cbOperacao.addItem(operacao_especie_pagamento.name());
        }

        for (TipoContaEspeciePagamento tipo_conta_especie_pagamento : TipoContaEspeciePagamento.values() ){
          cbTipoConta.addItem(tipo_conta_especie_pagamento.name());
        }
    }

    public void setPosicao() {
         Dimension d = this.getDesktopPane().getSize();
         this.setLocation(15 + (d.width - this.getSize().width) / 5, 15 + (d.height - this.getSize().height) / 5);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDadosEspeciePagamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbOperacao = new javax.swing.JComboBox();
        edtDescricao = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoConta = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Cadastro de Espécie");

        pDadosEspeciePagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Especie Lançamento"));

        jLabel1.setText("Código Espécie");

        jLabel2.setText("Descrição");

        jLabel3.setText("Operação");

        cbOperacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione.." }));

        lbCodigo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(0, 0, 255));
        lbCodigo.setText("codigo");

        jLabel4.setText("Tipo de Conta");

        cbTipoConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione.." }));

        javax.swing.GroupLayout pDadosEspeciePagamentoLayout = new javax.swing.GroupLayout(pDadosEspeciePagamento);
        pDadosEspeciePagamento.setLayout(pDadosEspeciePagamentoLayout);
        pDadosEspeciePagamentoLayout.setHorizontalGroup(
            pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosEspeciePagamentoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigo)
                    .addComponent(edtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pDadosEspeciePagamentoLayout.setVerticalGroup(
            pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosEspeciePagamentoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosEspeciePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDadosEspeciePagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDadosEspeciePagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOperacao;
    private javax.swing.JComboBox cbTipoConta;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JPanel pDadosEspeciePagamento;
    // End of variables declaration//GEN-END:variables

   private EspeciePagamento especie_pagamento;


   public EspeciePagamento getEspeciePagamento() throws PessoaisException {
       
       String operacao = (String) cbOperacao.getSelectedItem();

       if (operacao == "") {
          throw new PessoaisException("Não foi informada a operacao.");
       } else {
               especie_pagamento.setOperacao(operacao);
              }
        String descricao = edtDescricao.getText();

        if (descricao == null || descricao.trim().equals("")){
           edtDescricao.requestFocus();
           throw new PessoaisException("Não foi informado o nome do sócio.");
        } else {
            especie_pagamento.setDescricao(descricao);
          }
        String tipo_conta = (String) cbTipoConta.getSelectedItem();

        if (tipo_conta == "") {
            throw new PessoaisException("Nao foi informado o tipo de conta");
        } else
            especie_pagamento.setTipo_conta(tipo_conta);


        return especie_pagamento;
   }

   public void limparCampos(){
     cbOperacao.setSelectedIndex(0);
     edtDescricao.setText(null);
     cbTipoConta.setSelectedIndex(0);
   }


   public void exibeDadosEspeciePagamento() {
      limparCampos();
      if (especie_pagamento.getId_especie_pagamento() != Constante.NOVO) {
          cbOperacao.setSelectedItem(especie_pagamento.getOperacao());
          edtDescricao.setText(especie_pagamento.getDescricao());
          cbTipoConta.setSelectedItem(especie_pagamento.getTipo_conta());
          lbCodigo.setText(String.valueOf(especie_pagamento.getId_especie_pagamento()));
       
      }
   }
}
