/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUITemplatePai.java
 *
 * Created on 20/02/2011, 10:05:09
 */

package visao.gui;

/**
 *
 * @author Marlon
 */
public class GUITemplatePai extends javax.swing.JInternalFrame {

    /** Creates new form GUITemplatePai */
    public GUITemplatePai() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bSair1 = new javax.swing.JButton();
        bSair2 = new javax.swing.JButton();
        bSair3 = new javax.swing.JButton();
        bSair4 = new javax.swing.JButton();
        bSair5 = new javax.swing.JButton();
        bSair6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(176, 176, 175));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bSair1.setBackground(new java.awt.Color(176, 176, 175));
        bSair1.setText("Novo");
        bSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSair1ActionPerformed(evt);
            }
        });

        bSair2.setBackground(new java.awt.Color(176, 176, 175));
        bSair2.setText("Sair");
        bSair2.setMaximumSize(new java.awt.Dimension(56, 28));
        bSair2.setMinimumSize(new java.awt.Dimension(56, 28));
        bSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSair2ActionPerformed(evt);
            }
        });

        bSair3.setBackground(new java.awt.Color(176, 176, 175));
        bSair3.setText("Alterar");
        bSair3.setMaximumSize(new java.awt.Dimension(56, 28));
        bSair3.setMinimumSize(new java.awt.Dimension(56, 28));
        bSair3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSair3ActionPerformed(evt);
            }
        });

        bSair4.setBackground(new java.awt.Color(176, 176, 175));
        bSair4.setText("Pesquisar");
        bSair4.setMaximumSize(new java.awt.Dimension(56, 28));
        bSair4.setMinimumSize(new java.awt.Dimension(56, 28));
        bSair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSair4ActionPerformed(evt);
            }
        });

        bSair5.setBackground(new java.awt.Color(176, 176, 175));
        bSair5.setText("Excluir");
        bSair5.setMaximumSize(new java.awt.Dimension(56, 28));
        bSair5.setMinimumSize(new java.awt.Dimension(56, 28));
        bSair5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSair5ActionPerformed(evt);
            }
        });

        bSair6.setBackground(new java.awt.Color(176, 176, 175));
        bSair6.setText("Imprimir");
        bSair6.setMaximumSize(new java.awt.Dimension(56, 28));
        bSair6.setMinimumSize(new java.awt.Dimension(56, 28));
        bSair6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSair6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSair3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSair5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSair6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSair4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSair2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bSair3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bSair4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bSair5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bSair6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSair1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSair1ActionPerformed

    private void bSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSair2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSair2ActionPerformed

    private void bSair3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSair3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSair3ActionPerformed

    private void bSair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSair4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSair4ActionPerformed

    private void bSair5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSair5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSair5ActionPerformed

    private void bSair6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSair6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSair6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSair1;
    private javax.swing.JButton bSair2;
    private javax.swing.JButton bSair3;
    private javax.swing.JButton bSair4;
    private javax.swing.JButton bSair5;
    private javax.swing.JButton bSair6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
