/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIPrincipal.java
 *
 * Created on 17/02/2011, 12:58:46
 */

package visao.gui;

import javax.swing.JFrame;

/**
 *
 * @author Marlon
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /** Creates new form GUIPrincipal */
    public GUIPrincipal() {
        initComponents();
      this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCEspeciePagamento = new javax.swing.JMenuItem();
        menuLancamento = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        menuInformacoes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contolar as Despesas Pessoais");

        menuCadastro.setText("Cadastros");

        menuCEspeciePagamento.setText("Espécie Despesas");
        menuCadastro.add(menuCEspeciePagamento);

        menuBar.add(menuCadastro);

        menuLancamento.setText("Lançamentos");
        menuBar.add(menuLancamento);

        menuRelatorio.setText("Relatórios");
        menuBar.add(menuRelatorio);

        menuSair.setText("Sair");
        menuBar.add(menuSair);

        menuInformacoes.setText("Informações");
        menuBar.add(menuInformacoes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCEspeciePagamento;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuInformacoes;
    private javax.swing.JMenu menuLancamento;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

}
